### ISSUE TITLE
integrate common environment mapping techniques

### ISSUE THREAD

**Issue by cgcostume** [cginternals/webgl-operate#114]
based on the blog example that is already prepared and based on my master's thesis

**Comment by cgcostume** [comment]
include the existing (internal) env-mapping demo and reference ERMT project ...

**Comment by p-otto** [comment]
> include the existing (internal) env-mapping demo and reference ERMT project ...

Done in #189 
Where should we reference ERMT? In the code or the example description?

**Comment by cgcostume** [comment]
goal is to create a kind of `EnvironmentRenderingPass` that decides which projection to use based on the input texture and its type (e.g., via enum)
