### ISSUE TITLE
switch to rollup bundling

### ISSUE THREAD

**Issue by cgcostume** [cginternals/webgl-operate#115]
https://github.com/rollup/rollup

**Comment by bwasty** [comment]
Working prototype: https://github.com/cginternals/webgl-operate/compare/master...bwasty:lib-esm-rollup
Mainly missing is `require` support for json and shaders (there are similar plugins for rollup, but they didn't work when I first tried and the glsl plugin doesn't support the `@import` syntax we use in shaders).

**Comment by cgcostume** [comment]
done: the restructuring of webgl-operate into smaller libraries ([haeley](https://github.com/halb3/)) using vite (which extends rollup) instead of webpack.
