### ISSUE TITLE
Mat4.from and quat.from not usable

### ISSUE THREAD

**Issue by milanpro** [cginternals/webgl-operate#140]
### Summary

When using mat4.from and quat.from the return value is a Float32Array, which is not compatible anymore to the mat4 or quat.

**Comment by cgcostume** [comment]
Thanks for reporting. Can you please provide an example?

**Comment by bwasty** [comment]
gl-matrix has strange types - a `mat4` actually _is_ a Float32Array, so it is safe to cast, e.g. `x as mat4`.
