### ISSUE TITLE
Typed initialize arguments

### ISSUE THREAD

**Issue by milanpro** [cginternals/webgl-operate#141]
Since Typescript does not tell me what i should put in the initialize methods of the various classes. Is there a way to find that out reliably? Right now i am just looking the examples up.
Maybe adding those to the code as a comment or a type would be helpful!

**Comment by bwasty** [comment]
You can see the concrete arguments in the protected `create` method of each class (in the generated docs, choose `Public/Protected` at the top to see it).
We're aware that this is not the best interface and are considering to refactor the initialization so we can put the types directly on `initialize`.

**Comment by cgcostume** [comment]
moved to [haeley-canvas](https://github.com/halb3/haeley-canvas/issues/2)
