### ISSUE TITLE
Labelrenderpass ndcoffset default or error message

### ISSUE THREAD

**Issue by milanpro** [cginternals/webgl-operate#150]
### Summary

Without setting the ndcoffset on the labelrenderpass, rendering is not possible.
So i thought it might be useful to set a default or throw an error which is more descriptive, since the error is thrown in the minified version with the following message `Failed to execute 'uniform2fv' on 'WebGL2RenderingContext'`

**Comment by cgcostume** [comment]
fixed in 79e2648201767e8be2139770baf78147e0b74bfd
