### ISSUE TITLE
experimental technology should be disablaeble

### ISSUE THREAD

**Issue by anne-gropler** [cginternals/webgl-operate#161]
The `Context` uses technology that is experimental, e.g., [blitFramebuffer](https://github.com/cginternals/webgl-operate/blob/master/source/context.ts#L850), which is used in `blitpass.ts`.
An application using webgl-operate should be able to opt-out of that (I am currently having a problem with `functionBlit()`, while `programBlit()` works perfectly fine).

Unfortunately, it is not possible to disable it:
`myContext._context.blitFramebuffer = undefined;`
does not work, since `_context` is a **protected** property of webgl-operate's `Context`.

Current workaround would be to fork webgl-operate and delete the codelines that are based on experimental technology; or use a hack like:
`(myContext as any)._context.blitFramebuffer = undefined;`

Apart from blitFramebuffer, `readBuffer` and `texImage3D ` are experimental, too.

**Comment by scheibel** [comment]
Although I support your point, the actual issue you state may be a defect within our code base.

**Comment by anne-gropler** [comment]
After hours of debugging, having issues with clearColor and drawBuffers -- yes, there might be a problem in my codebase, but I could it bring down to using `programBlit()` instead of `functionBlit()`.
If I use `functionBlit()`, there is a weird color blending, although blending is disabled (so is canvas alpha, premultipliedAlpha and preserveDrawingBuffer).

**Comment by scheibel** [comment]
Yes, I referred to webgl-operate :smile: 
We'll have to investigate further.
