### ISSUE TITLE
Reenable Variance Shadow Mapping (VSM)

### ISSUE THREAD

**Issue by p-otto** [cginternals/webgl-operate#185]
Currently VSM is commented out in`shadowpass.ts` since it looked buggy. The shadows seemed to not match the scene perfectly and were slightly curved.
This needs to be debugged, e.g. in the shadow mapping example, by reenabling the code and using ` this._shadowPass.initialize(ShadowPass.ShadowMappingType.VarianceShadowMapping, [1024, 1024], [512, 512]);` to enable VSM.

**Comment by cgcostume** [comment]
and review/refine shadow pass
