### ISSUE TITLE
Facade for MAX_DRAW_BUFFERS / MAX_DRAW_BUFFERS_WEBGL

### ISSUE THREAD

**Issue by anne-gropler** [cginternals/webgl-operate#201]
When drawBuffers is supported (either through webgl1-extension or webgl2-default), the maximum number of supported draw buffers can be queried by `gl.getParameter`. However, the enum is different depending on the webgl version:
* webgl1: MAX_DRAW_BUFFERS_WEBGL
* webgl2: MAX_DRAW_BUFFERS

Since webgl-operate already offers a GL2Facade, this enum difference should be handled by the facade, too.

**Comment by cgcostume** [comment]
can be done now using `context.param(context.gl2facade.MAX_DRAW_BUFFERS)`
