### ISSUE TITLE
Glyphs are rendered distorted on some browser-OS-Hardware-configurations.

### ISSUE THREAD

**Issue by anne-gropler** [cginternals/webgl-operate#208]
See attached images. The correct glyphs are shown, but apparently the texture access results in wrong contours.

Configuration:
    Windows 10 Pro 1903
    Chrome: Version 78.0.3904.108 (Offizieller Build) (64-Bit)
    Graphic card: NVIDIA GeForce GTX 1080

It does work fine on Firefox, Edge and ie11. I also attached the full diagnostic info for Firefox and Chrome.

![image](https://user-images.githubusercontent.com/5690856/70329111-e6594000-183a-11ea-9eea-4621aea6af84.png)
![image (1)](https://user-images.githubusercontent.com/5690856/70329112-e6594000-183a-11ea-9d87-edc2b16232fc.png)

[webgl_diagnostic_chrome.txt](https://github.com/cginternals/webgl-operate/files/3932543/webgl_diagnostic_chrome.txt)
[webgl_diagnostics_firefox.txt](https://github.com/cginternals/webgl-operate/files/3932544/webgl_diagnostics_firefox.txt)

**Comment by scheibel** [comment]
Does the rendering errors occur on newly tested machines or was the rendering correct some time ago?

**Comment by c-goldschmidt** [comment]
I believe it did work some weeks ago, but i cannot pinpoint the date/version when it broke.

**Comment by scheibel** [comment]
This behavior occurs when using Google swiftshader software rendering.

**Comment by anne-gropler** [comment]
Minimal working example for shadertoy (assign any texture to Channel0)
```
float utilityFunction(float t, float value) {
    return t;
}

float subFunction(float t, vec2 uv) {
    return utilityFunction(t, texture(iChannel0, uv)[0]);
}

void mainImage( out vec4 fragColor, in vec2 fragCoord ) {
    // Normalized pixel coordinates (from 0 to 1)
    vec2 v_uv = fragCoord/iResolution.xy;

    float a = subFunction(0.5, v_uv);    
    fragColor = vec4(1.0, a, 0.0, 1.0);
}
```
Should render a completely orange frame, but instead renders a gradiant from red to yellow (left to right).

**Comment by anne-gropler** [comment]
Bug was reported to Google:
https://issuetracker.google.com/u/1/issues/146041290

I will apply a workaround and open a PR with it.
