### ISSUE TITLE
Tiled-Camera-Generator rendering artefacts

### ISSUE THREAD

**Issue by MartinBuessemeyer** [cginternals/webgl-operate#210]
Using the ```tiledcameragenerator.ts``` produces small differences compared to non tiled rendering.
![untiled](https://user-images.githubusercontent.com/39387258/70628633-c9e94900-1c28-11ea-9b46-c427fc51bbc8.png)
![scanline](https://user-images.githubusercontent.com/39387258/70628642-cf469380-1c28-11ea-952f-561a0b7f8593.png)
![diff-scanline](https://user-images.githubusercontent.com/39387258/70628655-d4a3de00-1c28-11ea-90fb-665f1cd9c620.png)

**Comment by cgcostume** [comment]
moved to [haeley-math](https://github.com/halb3/haeley-math/issues/2)
