### ISSUE TITLE
Add function that maps texture unit to uniform location

### ISSUE THREAD

**Issue by MartinBuessemeyer** [cginternals/webgl-operate#243]
Currently we have a lot of magic numbers that are actually duplicate.

Suppose we have:

`this._cubemap = new TextureCube();`

We then need to get the location:
`gl.uniform1i(this._program.uniform('u_cubemap'), 3);`

And then activate (and bind) it with:
`this._cubemap.bind(gl.TEXTURE3)`

Therefore a mapping from `gl.TEXTUREX => X` where `X` is the number would be helpful.

With this we could simply declare a Variable:
`this._cubeMapEnum = GLenum`;
And then set it once in the initialization to `this._cubeMapEnum = gl.TEXTURE0;`
Then we can just use the mapping and the variable to get all the necessary values.

I would add such a function to the auxiliaries.

**Comment by MartinBuessemeyer** [comment]
What do you think of this idea @cgcostume?

**Comment by cgcostume** [comment]
This is something that we cannot assume for any arbitrary rendering, e.g., one might want to use an environment texture for multiple rendering passes, each of which has the texture at a different texture unit. The idea itself is correct for a strict rendering engine you might build on top of webgl-operate.
