### ISSUE TITLE
Improve release workflow (GitHub releases & automation)

### ISSUE THREAD

**Issue by bwasty** [cginternals/webgl-operate#83]
Proposed workflow:
- add these to `scripts` in package.json: 
  - `"version": "<update-versions-script>" $npm_package_version` (should do what all the `prepare patch/minor` commits do now; `$npm_package_version` contains the new version number)
  - `"postversion": "git push && git push --tags"`
- For each release:
  - `npm version <semver-version>`
     - optional: create GitHub release with changelog based on uploaded tag
  - `npm publish`

EDIT: Here's an excerpt from the `npm version` docs to make clear what happens:
       

>        If preversion, version, or postversion are in the scripts property of the
>        package.json, they will be executed as part of running npm version.
> 
>        The exact order of execution is as follows:
> 
>        1. Check to make sure the git working directory is clean  before  we  get
>           started.   Your  scripts  may add files to the commit in future steps.
>           This step is skipped if the --force flag is set.
> 
>        2. Run the preversion script. These scripts have access to the  old  ver-
>           sion  in  package.json.  A typical use would be running your full test
>           suite before deploying.  Any files you want added to the commit should
>           be explicitly added using git add.
> 
>        3. Bump  version in package.json as requested (patch, minor, major, etc).
> 
>        4. Run the version script. These scripts have access to the  new  version
>           in  package.json (so they can incorporate it into file headers in gen-
>           erated files for example).  Again, scripts should explicitly add  gen-
>           erated files to the commit using git add.
> 
>        5. Commit and tag.
> 
>        6. Run  the  postversion  script.  Use  it to clean up the file system or
>           automatically push the commit and/or tag.
> 
> 
>        Take the following example:
> 
>          "scripts": {
>            "preversion": "npm test",
>            "version": "npm run build && git add -A dist",
>            "postversion": "git push && git push --tags && rm -rf build/temp"
>          }

**Comment by cgcostume** [comment]
implemented and already used for 0.3.8 release, thanks for pushing this topic! I made the `prepack` utilize the `preversion` script, which in turn uses the `ci` script. The `ci` script now runs all scripts in parallel which saves about 1 minute of travis-ci processing time.
